# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Baliu-Fiamenghi\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shadow_tracer\shadow_tracer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShadowTracerDialogBase(object):
    def setupUi(self, ShadowTracerDialogBase):
        ShadowTracerDialogBase.setObjectName("ShadowTracerDialogBase")
        ShadowTracerDialogBase.resize(368, 426)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        ShadowTracerDialogBase.setFont(font)
        self.button_box = QtWidgets.QDialogButtonBox(ShadowTracerDialogBase)
        self.button_box.setGeometry(QtCore.QRect(150, 390, 201, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.groupBox = QtWidgets.QGroupBox(ShadowTracerDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 341, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 27, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(170, 27, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.z_spin = QtWidgets.QSpinBox(self.groupBox)
        self.z_spin.setGeometry(QtCore.QRect(170, 60, 121, 22))
        self.z_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.z_spin.setMaximum(90)
        self.z_spin.setProperty("value", 90)
        self.z_spin.setObjectName("z_spin")
        self.azim_spin = QtWidgets.QSpinBox(self.groupBox)
        self.azim_spin.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.azim_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.azim_spin.setMaximum(360)
        self.azim_spin.setDisplayIntegerBase(10)
        self.azim_spin.setObjectName("azim_spin")
        self.azim_dial = QtWidgets.QDial(self.groupBox)
        self.azim_dial.setGeometry(QtCore.QRect(30, 80, 101, 91))
        self.azim_dial.setMaximum(359)
        self.azim_dial.setSingleStep(1)
        self.azim_dial.setPageStep(0)
        self.azim_dial.setProperty("value", 180)
        self.azim_dial.setSliderPosition(180)
        self.azim_dial.setOrientation(QtCore.Qt.Horizontal)
        self.azim_dial.setInvertedAppearance(False)
        self.azim_dial.setInvertedControls(False)
        self.azim_dial.setWrapping(True)
        self.azim_dial.setNotchesVisible(False)
        self.azim_dial.setObjectName("azim_dial")
        self.z_slider = QtWidgets.QSlider(self.groupBox)
        self.z_slider.setGeometry(QtCore.QRect(220, 90, 20, 81))
        self.z_slider.setMaximum(90)
        self.z_slider.setSingleStep(1)
        self.z_slider.setProperty("value", 90)
        self.z_slider.setSliderPosition(90)
        self.z_slider.setOrientation(QtCore.Qt.Vertical)
        self.z_slider.setObjectName("z_slider")
        self.groupBox_2 = QtWidgets.QGroupBox(ShadowTracerDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 341, 141))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spin_floor = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_floor.setGeometry(QtCore.QRect(20, 40, 121, 22))
        self.spin_floor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spin_floor.setDecimals(1)
        self.spin_floor.setMaximum(99999.0)
        self.spin_floor.setSingleStep(0.1)
        self.spin_floor.setObjectName("spin_floor")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.combo_elevation = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_elevation.setGeometry(QtCore.QRect(20, 90, 301, 22))
        self.combo_elevation.setObjectName("combo_elevation")

        self.retranslateUi(ShadowTracerDialogBase)
        self.azim_spin.valueChanged['int'].connect(self.azim_dial.setValue)
        self.azim_dial.valueChanged['int'].connect(self.azim_spin.setValue)
        self.z_slider.valueChanged['int'].connect(self.z_spin.setValue)
        self.z_spin.valueChanged['int'].connect(self.z_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(ShadowTracerDialogBase)

    def retranslateUi(self, ShadowTracerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ShadowTracerDialogBase.setWindowTitle(_translate("ShadowTracerDialogBase", "Shadow Tracer"))
        self.groupBox.setTitle(_translate("ShadowTracerDialogBase", "SUN POSITION"))
        self.label_7.setText(_translate("ShadowTracerDialogBase", "Azimuth \n"
"(North is 0°, clockwise):"))
        self.label_8.setText(_translate("ShadowTracerDialogBase", "Zenith \n"
"(0° - horizontal, 90° - vertical):"))
        self.groupBox_2.setTitle(_translate("ShadowTracerDialogBase", "REFERENCE"))
        self.label_11.setText(_translate("ShadowTracerDialogBase", "Floor Level:"))
        self.label_12.setText(_translate("ShadowTracerDialogBase", "Elevation Layer:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShadowTracerDialogBase = QtWidgets.QDialog()
    ui = Ui_ShadowTracerDialogBase()
    ui.setupUi(ShadowTracerDialogBase)
    ShadowTracerDialogBase.show()
    sys.exit(app.exec_())

